[package]
name = "cargo-expand"
version = "0.4.19"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Wrapper around rustc --pretty=expanded. Shows the result of macro expansion and #[derive] expansion."
repository = "https://github.com/dtolnay/cargo-expand"
documentation = "https://github.com/dtolnay/cargo-expand"
keywords = ["cargo", "subcommand", "expanded"]
categories = ["development-tools::cargo-plugins", "development-tools::debugging"]
edition = "2018"
readme = "README.md"

[dependencies]
atty = "0.2"
bat = "0.13"
proc-macro2 = "1.0"
quote = { version = "1.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
syn-select = "0.2"
tempfile = "3.0"
termcolor = "1.0"
toml = "0.5"
toolchain_find = "0.1"

[dependencies.syn]
version = "1.0"
default-features = false
features = ["full", "parsing", "printing", "visit-mut"]

[badges]
travis-ci = { repository = "dtolnay/cargo-expand" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
